### ISSUE TITLE
Add build for linux-ppc64le

### ISSUE THREAD

**Issue by sdebionne** [conda-forge/pyfai-feedstock#48]
Adding `linux-ppc64le` as a target platform is pretty straightforward but some direct or indirect dependencies are not built yet for ppc64le. Here is a non exhaustive list:

 - [ ] fabio conda-forge/fabio-feedstock#32
 - [ ] hdf5plugin conda-forge/hdf5plugin-feedstock#17
 - [ ] silx-base conda-forge/silx-feedstock#37

Installing from `pypi` works fine, but with a few glitches, e.g. the entry points are not properly installed.

Once the dependencies are satisfied, I'll open a MR to add the `linux-ppc64le` platform.

**Comment by kif** [comment]
Since we have all those tools running on power9, I foresee no major issue.
Thanks for proposing your help

**Comment by t20100** [comment]
This was added in PR #64
